project_name: grpc-examples
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
#     # you may remove this if you don't need go generate
#     - go generate ./...
builds:
  - dir: examples/helloworld/greeter_client
    id: "greeter_client"
    binary: greeter_client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - dir: examples/helloworld/greeter_server
    id: "greeter_server"
    binary: greeter_server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
